language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install flake8 pylint coveralls
script:
- flake8 aio_androidtv/ && pylint aio_androidtv/ && coverage run --source aio_androidtv setup.py test
after_success:
- coveralls
